# NOTE: requests must be separated by ###

# route parameters (`req.params`)
GET http://localhost:8888/api/harry potter/paragraphs/3/html/5/25/5/14

###

GET http://localhost:8888/api/harry potter//2//3///14

###

# query string parameters (`req.query`)
GET http://localhost:8888/api?query=harry potter&quantity=3&sentencesPerParagraph[min]=3&wordsPerSentence[max]=21&sentencesPerParagraph[max]=10&format=html&wordsPerSentence[min]=10

###

# request body (`req.body`), must include json middleware
GET http://localhost:8888/api/
Content-Type: application/json

{
    "query": "harry potter",
    "quantity": 1,
    "format": "html",
    "sentencesPerParagraph": {
      "min": 25,
      "max": 50
    }
}

###

# request body (`req.body`), must include urlencoded middleware
GET http://localhost:8888/api/
Content-Type: application/x-www-form-urlencoded

query=harry potter
&quantity=2
&sentencesPerParagraph[max]=20
&format=html
